# Generated by Django 3.2.9 on 2021-11-07 14:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('days', models.PositiveIntegerField(default=0, verbose_name='days before launch')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step', models.PositiveIntegerField(default=0, verbose_name='Actual step')),
                ('stepDate', models.DateField(default=datetime.date.today, verbose_name='Last step date')),
                ('firstName', models.CharField(max_length=50, verbose_name='First name')),
                ('lastName', models.CharField(max_length=50, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.sequence')),
            ],
        ),
        migrations.CreateModel(
            name='EmailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveIntegerField(default=0, verbose_name='Days before send')),
                ('model', models.TextField(verbose_name='Model')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.sequence')),
            ],
        ),
    ]
