# Generated by Django 3.2.9 on 2021-11-07 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequence',
            name='days',
        ),
    ]
