# Generated by Django 3.2.9 on 2021-11-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_remove_sequence_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailmodel',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='step',
            field=models.PositiveIntegerField(default=0, verbose_name='Positioning of email'),
        ),
    ]
