# Generated by Django 3.2.9 on 2021-11-07 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0006_alter_emailmodel_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('email', 'sequence')},
        ),
    ]
