# Generated by Django 3.2.9 on 2021-11-07 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0007_alter_person_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='step',
            new_name='nextStep',
        ),
        migrations.RemoveField(
            model_name='person',
            name='stepDate',
        ),
        migrations.AddField(
            model_name='person',
            name='lastActionDate',
            field=models.DateField(default=datetime.date.today, verbose_name='Last action date'),
        ),
    ]
