# Generated by Django 3.2.9 on 2021-11-07 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0009_alter_emailmodel_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmodel',
            name='days',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Days before send'),
        ),
    ]
