# Generated by Django 3.2.9 on 2021-11-07 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0010_alter_emailmodel_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='lastActionDate',
        ),
        migrations.AddField(
            model_name='person',
            name='nextStepDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Next action date'),
        ),
    ]
