# Generated by Django 3.2.9 on 2021-11-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0011_auto_20211107_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='nextStepDate',
            field=models.DateField(verbose_name='Next action date'),
        ),
    ]
