# Generated by Django 3.2.9 on 2021-11-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0012_alter_person_nextstepdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='responseEmail',
            field=models.EmailField(default='test@test.fr', max_length=254, verbose_name='Email for responses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sequence',
            name='senderName',
            field=models.CharField(default='test@test.fr', max_length=150, verbose_name='Name of the sender'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sequence',
            name='subjectEmail',
            field=models.CharField(default='terst@test.fr', max_length=150, verbose_name='Subject of emails'),
            preserve_default=False,
        ),
    ]
