# Generated by Django 3.2.9 on 2021-11-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0013_auto_20211107_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequence',
            name='responseEmail',
        ),
        migrations.AddField(
            model_name='sequence',
            name='replyEmail',
            field=models.EmailField(default='antoine@joyger.fr', max_length=254, verbose_name='Email for reply-to'),
            preserve_default=False,
        ),
    ]
