# Generated by Django 3.2.9 on 2021-11-18 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0019_person_friendcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emails.sequence'),
        ),
    ]
